### ISSUE TITLE
依赖下不下来呢 老铁

### ISSUE THREAD

**Issue by jerryzn** [DevilsHuan/vue-m-stock#2]
Error: Cannot find module 'semver'
Require stack:
- D:\phpStudy\WWW\vue\stock\node_modules\_@vue_cli-service@3.12.1@@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\vue\stock\node_modules\_@vue_cli-service@3.12.1@@vue\cli-service\bin\vue-cli-service.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\vue\\stock\\node_modules\\_@vue_cli-service@3.12.1@@vue\\cli-service\\bin\\vue-cli-service.js'
  ]
}

**Comment by jerryzn** [comment]
无法运行

**Comment by jerryzn** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vue-async-module - Not found
npm ERR! 404
npm ERR! 404  'vue-async-module@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'stock'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
